"""index guid columns and chat_id in messages

Revision ID: 31d902595d49
Revises: fcd981f09e8d
Create Date: 2025-02-06 22:48:22.017491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d902595d49'
down_revision: Union[str, None] = 'fcd981f09e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('guid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_chatbots_guid'), 'chatbots', ['guid'], unique=True)

    op.drop_constraint('uq_chats_guid', 'chats', type_='unique')
    op.create_index(op.f('ix_chats_guid'), 'chats', ['guid'], unique=True)

    op.drop_constraint('friend_requests_guid_key', 'friend_requests', type_='unique')
    op.create_index(op.f('ix_friend_requests_guid'), 'friend_requests', ['guid'], unique=True)

    op.drop_constraint('uq_messages_guid', 'messages', type_='unique')
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)

    op.create_index(op.f('ix_messages_guid'), 'messages', ['guid'], unique=True)
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('uq_users_guid', 'users', type_='unique')
    op.create_index(op.f('ix_users_guid'), 'users', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guid'), table_name='users')
    op.create_unique_constraint('uq_users_guid', 'users', ['guid'])
    
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_index(op.f('ix_messages_guid'), table_name='messages')

    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.create_unique_constraint('uq_messages_guid', 'messages', ['guid'])

    op.drop_index(op.f('ix_friend_requests_guid'), table_name='friend_requests')
    op.create_unique_constraint('friend_requests_guid_key', 'friend_requests', ['guid'])

    op.drop_index(op.f('ix_chats_guid'), table_name='chats')
    op.create_unique_constraint('uq_chats_guid', 'chats', ['guid'])

    op.drop_index(op.f('ix_chatbots_guid'), table_name='chatbots')
    op.drop_column('chatbots', 'guid')
    # ### end Alembic commands ###
