"""add openai token and has_bot

Revision ID: 57a6c97991b4
Revises: a3805b07c30d
Create Date: 2025-01-29 00:23:46.459238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a6c97991b4'
down_revision: Union[str, None] = 'a3805b07c30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('has_bot', sa.Boolean(), nullable=True))
    op.execute("UPDATE chats SET has_bot = FALSE WHERE has_bot IS NULL")
    op.alter_column('chats', 'has_bot', nullable=False)

    op.add_column('users', sa.Column('openai_token', sa.String(length=255), nullable=True))
    op.execute("UPDATE users SET openai_token = '' WHERE openai_token IS NULL")
    op.alter_column('users', 'openai_token', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('users', 'openai_token')
    op.drop_column('chats', 'has_bot')
    # ### end Alembic commands ###
