"""add role to user

Revision ID: ac0fd1d28bee
Revises: 31d902595d49
Create Date: 2025-02-07 01:17:08.980626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0fd1d28bee'
down_revision: Union[str, None] = '31d902595d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


userrole_enum = sa.Enum('ADMIN', 'USER', name='userrole')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True))
    op.execute("UPDATE users SET role = 'USER' WHERE role IS NULL")
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
