"""add chatbots

Revision ID: fcd981f09e8d
Revises: 57a6c97991b4
Create Date: 2025-02-04 18:27:12.028666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd981f09e8d'
down_revision: Union[str, None] = '57a6c97991b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('ASSISTANT', 'DEFAULT', name='chatbottype'), nullable=False),
    sa.Column('system_prompt', sa.TEXT(), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_bots_association',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bot_id', 'chat_id')
    )
    op.drop_column('chats', 'has_bot')
    op.add_column('friend_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend_requests', 'updated_at')

    op.add_column('chats', sa.Column('has_bot', sa.Boolean(), nullable=True))
    op.execute("UPDATE chats SET has_bot = FALSE WHERE has_bot IS NULL")
    op.alter_column('chats', 'has_bot', nullable=False)

    op.drop_table('chat_bots_association')
    op.drop_table('chatbots')
    op.execute("DROP TYPE IF EXISTS chatbottype")
    # ### end Alembic commands ###
