lexik_jwt_authentication:
    private_key_path: '%env(resolve:JWT_SECRET_KEY)%'
    public_key_path: '%env(resolve:JWT_PUBLIC_KEY)%'
    #secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    #public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: 'passu'
    #private_key_path: '/config/jwt/private.pem' # TODO
    #public_key_path: '/config/jwt/public.pem'   # TODO
    #pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 7200
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS256
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization